### ISSUE TITLE
Update-Modules.ps1 Needs small update

### ISSUE THREAD

**Issue by kpcintegrations** [jimbrig/PSScripts#17]
There's a part of the code that's "if(!Test-IsAdmin)" It needs to be "if(!(Test-IsAdmin))" otherwise man Update-PSModules.ps1 throws an error.

**Comment by jimbrig** [comment]
@kpcintegrations 'preciate that, nice catch!

**Comment by jimbrig** [comment]
> There's a part of the code that's "if(!Test-IsAdmin)" It needs to be "if(!(Test-IsAdmin))" otherwise man Update-PSModules.ps1 throws an error.

New version published: https://www.powershellgallery.com/packages/Update-PSModules/1.0.4 - let me know if it works correctly for you now.

Thanks,
Jimmy
